name: Auto PR for UI Suite Branches

on:
  push:
    branches:
      - "ut/suite-for-ui-1"

  workflow_dispatch: # Allow manual triggers

jobs:
  auto-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Check for existing PR
        id: check-pr
        uses: peter-evans/close-pull-request@v2
        with:
          token: ${{ secrets.BOT_TOKEN }}
          search-query: "repo:${{ github.repository }} is:pr is:open head:${{ github.ref_name }} base:develop"

      - name: Create Pull Request
        if: steps.check-pr.outputs.closed_count == 0
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.BOT_TOKEN }}
          base: develop
          head: ${{ github.ref_name }}
          title: "Auto PR: ${{ github.ref_name }}"
          body: |
            This pull request was automatically created by a GitHub Action.
            Branch: ${{ github.ref_name }}
            Target: develop
